packages:
  - apps/*
  - packages/*

catalog:
  '@trpc/client': ^11.5.0
  '@trpc/server': ^11.5.0
  '@types/node': ^22.13.11
  better-auth: ^1.3.28
  dotenv: ^17.2.2
  drizzle-orm: 0.44.7
  hono: ^4.8.2
  tsdown: ^0.15.5
  typescript: ^5.8.2
  zod: ^4.1.11
